GET http://localhost:8080/api/pracowniks

###

GET http://localhost:8080/api/pracowniks/1

###

GET http://localhost:8080/api/pracowniks/5

###

POST http://localhost:8080/api/pracowniks
Content-Type: application/json

{
  "id": 7,
  "imie": "Andrzej"
}

###

PUT http://localhost:8080/api/pracowniks/7
Content-Type: application/json

{
  "imie": "Robert"
}

###

DELETE http://localhost:8080/api/pracowniks/1

###

GET http://localhost:8080/api/szefs

###

GET http://localhost:8080/api/szefs/1

###

GET http://localhost:8080/api/szefs/1/pracowniks

###

GET http://localhost:8080/api/szefs/1/pracowniks/5

###


POST http://localhost:8080/api/szefs
Content-Type: application/json

{
  "id": 4,
  "imie": "Kacper"
}
###
PUT http://localhost:8080/api/szefs/4
Content-Type: application/json

{
  "imie": "Robert"
}

###
DELETE http://localhost:8080/api/szefs/4

###
POST http://localhost:8080/api/szefs/1/pracowniks
Content-Type: application/json

{
  "id": 9,
  "imie": "Tomek"
}

###
GET http://localhost:8080/api/szefs/1/pracowniks