GET http://localhost:8080/api/characters

###

GET http://localhost:8080/api/characters
Accept: application/xml

###

GET http://localhost:8080/api/characters/1

###

GET http://localhost:8080/api/characters/5

###

POST http://localhost:8080/api/characters
Content-Type: application/json

{
  "name": "Sigrid",
  "background": "No one special.",
  "age": 18,
  "strength": 12,
  "constitution": 12,
  "charisma": 12,
  "profession": "Bard"
}

###

PUT http://localhost:8080/api/characters/5
Content-Type: application/json

{
  "name": "Sir Sigrid",
  "background": "Someone well known.",
  "age": 30
}

###

DELETE http://localhost:8080/api/characters/5

###

GET http://localhost:8080/api/characters/1/portrait

###

PUT http://localhost:8080/api/characters/1/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="uhlbrecht.png'

< ../../src/main/resources/pl/edu/pg/eti/kask/rpg/configuration/avatar/uhlbrecht.png
--boundary--

###

GET http://localhost:8080/api/users/kevin/characters

###

GET http://localhost:8080/api/users/anonymous/characters

###

GET http://localhost:8080/api/users/kevin/characters/1

###

GET http://localhost:8080/api/users/anonymous/characters/1

###

GET http://localhost:8080/api/users/kevin/characters/5

###

POST http://localhost:8080/api/users/kevin/characters
Content-Type: application/json

{
  "name": "Sigrid",
  "background": "No one special.",
  "age": 18,
  "strength": 12,
  "constitution": 12,
  "charisma": 12,
  "profession": "Bard"
}

###
